import * as fs from 'node:fs';
import * as path from 'node:path';

/**
 * Scan a project to extract UI Framework and UI components
 * @param {string} projectRoot
 */
export function scanProject(projectRoot) {
  let pkg = {};
  const pkgPath = path.join(projectRoot, 'package.json');
  if (fs.existsSync(pkgPath)) {
    try {
      pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
    } catch {}
  }

  const deps = { ...(pkg.dependencies || {}), ...(pkg.devDependencies || {}) };
  
  // Detect UI library
  let uiLibrary = 'custom';
  if (deps['element-plus']) uiLibrary = 'element-plus';
  else if (deps['ant-design-vue']) uiLibrary = 'ant-design-vue';
  else if (deps['antd']) uiLibrary = 'ant-design-react';
  else if (deps['vuetify']) uiLibrary = 'vuetify';
  else if (deps['bootstrap-vue-next'] || deps['bootstrap-vue']) uiLibrary = 'bootstrap-vue';
  else if (deps['@chakra-ui/react'] || deps['@chakra-ui/vue-next']) uiLibrary = 'chakra-ui';
  else if (deps['radix-vue'] || deps['shadcn-vue']) uiLibrary = 'shadcn-vue';

  return {
    uiLibrary,
    dependencies: Object.keys(deps),
    packageJson: pkg
  };
}

/**
 * Extract DNA from a golden sample file (e.g. UserList.vue, ProductTable.tsx)
 * @param {string} filePath
 */
export function extractDna(filePath) {
  if (!fs.existsSync(filePath)) {
    throw new Error(`Golden sample file not found: ${filePath}`);
  }

  const content = fs.readFileSync(filePath, 'utf8');
  const ext = path.extname(filePath);

  // Discover shells & layouts
  const shellMatches = content.match(/<([A-Z][a-zA-Z0-9]*(?:Layout|Container|Page|Card))/g) || [];
  const shells = Array.from(new Set(shellMatches.map(m => m.replace('<', ''))));

  // Discover table / list components
  const tableMatches = content.match(/<([A-Z][a-zA-Z0-9]*(?:Table|List|Grid)|el-table|a-table|v-data-table)/g) || [];
  const tables = Array.from(new Set(tableMatches.map(m => m.replace('<', ''))));

  // Discover form / widget inputs
  const widgetMatches = content.match(/<([A-Z][a-zA-Z0-9]*(?:Input|Select|DatePicker|Button|Tag|Badge)|el-[a-z-]+|a-[a-z-]+|v-[a-z-]+)/g) || [];
  const widgets = Array.from(new Set(widgetMatches.map(m => m.replace('<', ''))));

  return {
    filePath,
    ext,
    shells: shells.length > 0 ? shells : ['CustomShell'],
    tables: tables.length > 0 ? tables : ['CustomTable'],
    widgets: widgets.slice(0, 20),
    rawContent: content
  };
}

/**
 * Generate design.registry.json based on extracted DNA
 * @param {object} params
 */
export function generateDesignRegistry({ uiLibrary, shells, widgets, outputDir }) {
  const primaryShell = shells[0] || 'CustomLayout';
  
  const registry = {
    $schema: 'https://flowgrid.dev/schemas/design-registry.json',
    uiLibrary,
    shells: {
      [primaryShell]: {
        tag: `#shell: ${primaryShell}`,
        description: `Primary application layout scanned from project DNA`,
        status: 'implemented'
      }
    },
    fieldWidgets: {},
    componentAliases: {}
  };

  for (const widget of widgets) {
    const key = widget.replace(/^[a-z]+-/, '').replace(/^[A-Z]/, c => c.toUpperCase());
    registry.fieldWidgets[key] = {
      tag: `#widget: ${key}`,
      component: widget,
      status: 'implemented'
    };
  }

  const registryDir = path.join(outputDir, 'registries');
  fs.mkdirSync(registryDir, { recursive: true });
  const registryPath = path.join(registryDir, 'design.registry.json');
  fs.writeFileSync(registryPath, JSON.stringify(registry, null, 2) + '\n');

  // Also export local lexicon file for ArtifactGraph SQLite ingestion
  const lexiconDir = path.join(outputDir, 'lexicon');
  fs.mkdirSync(lexiconDir, { recursive: true });
  const lexiconLines = [
    `# Local project custom tags lexicon generated by FlowGrid`,
    `#shell: ${primaryShell}`,
    ...widgets.map(w => {
      const key = w.replace(/^[a-z]+-/, '').replace(/^[A-Z]/, c => c.toUpperCase());
      return `#widget: ${key} · ${w}`;
    })
  ];
  fs.writeFileSync(path.join(lexiconDir, 'registry-tags.en.txt'), lexiconLines.join('\n') + '\n');

  return { registryPath, registry };
}

/**
 * Parameterize a sample into a Handlebars template
 * @param {object} params
 */
export function parameterizeTemplate({ sampleContent, outputDir, templateName = 'list.vue.hbs' }) {
  let template = sampleContent;

  // Generic parameterization of titles, entity names
  template = template.replace(/["']([A-Z][a-zA-Z0-9]+)\s+(Management|List|Index|Danh sách)["']/g, '"{{pascalCase entity}} $2"');
  template = template.replace(/api\/v\d+\/([a-z-]+)/g, 'api/v1/{{kebabCase entity}}');

  const templatesDir = path.join(outputDir, 'templates');
  fs.mkdirSync(templatesDir, { recursive: true });
  const templatePath = path.join(templatesDir, templateName);
  fs.writeFileSync(templatePath, template);

  return { templatePath };
}
